# ProMould - Pragmatic Analysis Configuration
# Catches critical errors while allowing flexibility for warnings/infos

include: package:flutter_lints/flutter.yaml

analyzer:
  # Only critical errors block builds
  errors:
    # Critical errors that must be fixed
    unused_import: error
    unused_element: warning
    dead_code: warning
    invalid_assignment: error
    undefined_identifier: error
    not_assigned_potentially_non_nullable_local_variable: error
    
    # Important warnings
    avoid_types_as_parameter_names: warning
    use_build_context_synchronously: warning
    
    # Style suggestions (don't block builds)
    avoid_print: info
    prefer_const_constructors: info
    prefer_const_literals_to_create_immutables: info
    prefer_const_declarations: info
    unnecessary_to_list_in_spreads: info
    
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
    - "build/**"
    - "lib/firebase_options.dart"

linter:
  rules:
    # Critical error prevention only
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - no_duplicate_case_values
    - test_types_in_equals
    - throw_in_finally
    - unrelated_type_equality_checks
    - valid_regexps
    
    # Essential style (non-blocking)
    - avoid_print
    - camel_case_types
    - curly_braces_in_flow_control_structures
    - empty_catches
    - empty_constructor_bodies
    - library_names
    - library_prefixes
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_is_empty
    - prefer_is_not_empty
    - unnecessary_null_in_if_null_operators
    - unnecessary_this
    - use_key_in_widget_constructors
